version: '3'

services:
  web:
    image: mcyprian/sme-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SMECONFIG: "production"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - "db"

  db:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
